# Generated by Django 4.1.7 on 2023-05-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('brief_details', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=255, unique=True)),
                ('application_email', models.EmailField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('job_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=300)),
                ('required_connect', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
        ),
    ]
