# Generated by Django 4.1.7 on 2023-05-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
